### ISSUE TITLE
setImmediate is not defined

### ISSUE THREAD

**Issue by evbogue** [pull-stream/pull-next#4]
I upgraded to the latest version of `pull-next` in minbase, and started getting a lot of `setImmediate is not defined` errors that I tracked back to this module. I think setimmediate is loaded by default in Electron but isn't present in browsers?

**Comment by evbogue** [comment]
@dominictarr  I guess we need to require this? https://www.npmjs.com/package/setimmediate

**Comment by dominictarr** [comment]
haha wow that is nearly 200 lines of code and all we need is to fallback in setTimeout

**Comment by dominictarr** [comment]
fixed in c8eba9aab04706ddbd7117ae895ae7c8ff2999bd
1.0.1
